# Generated by Django 6.0.3 on 2026-03-27 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('posts', '0002_post_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.category')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcategory', to='posts.post')),
            ],
        ),
    ]
